name: FTC Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      # JDK 17 satisfies both setup-android and modern AGP
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Assemble Debug APK
        run: ./gradlew --no-daemon :FtcRobotController:assembleDebug

      # (Debug) show where Gradle actually put the APK(s)
      - name: List APKs
        run: |
          echo "Searching for APKs under $PWD ..."
          find . -type f -name "*.apk" -print | sort || true

      # Upload any APK(s) we find (robust glob)
      - name: Upload APK(s)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-apks
          path: |
            **/*.apk


      # Optional: add lint once build passes
      # - name: Run Lint
      #   run: ./gradlew --no-daemon :FtcRobotController:lint :TeamCode:lint
      # - name: Upload Lint Reports
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: lint-reports
      #     path: |
      #       FtcRobotController/build/reports/lint-results*.* 
      #       TeamCode/build/reports/lint-results*.*
